import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // Create default admin user
  const passwordHash = await bcrypt.hash('admin123', 12);
  const user = await prisma.user.upsert({
    where: { email: 'admin@mspops.local' },
    update: {},
    create: {
      email: 'admin@mspops.local',
      name: 'Admin',
      passwordHash,
      role: 'admin',
    },
  });

  // Create Technology Pillars
  const pillars = [
    { name: 'Azure', icon: 'cloud', color: '#0078D4', sortOrder: 1 },
    { name: 'Entra ID', icon: 'shield', color: '#0078D4', sortOrder: 2 },
    { name: 'AD DS', icon: 'users', color: '#6B7280', sortOrder: 3 },
    { name: 'Windows Server', icon: 'server', color: '#0078D4', sortOrder: 4 },
    { name: 'VMware/Hyper-V', icon: 'layers', color: '#607078', sortOrder: 5 },
    { name: 'Networking', icon: 'network', color: '#10B981', sortOrder: 6 },
    { name: 'Security/SOC', icon: 'lock', color: '#EF4444', sortOrder: 7 },
    { name: 'SQL', icon: 'database', color: '#CC2927', sortOrder: 8 },
    { name: 'DevOps/Jenkins', icon: 'git-branch', color: '#F59E0B', sortOrder: 9 },
    { name: 'Automation/n8n', icon: 'zap', color: '#8B5CF6', sortOrder: 10 },
    { name: 'Backups/DR', icon: 'hard-drive', color: '#6366F1', sortOrder: 11 },
    { name: 'Certificates/TLS', icon: 'key', color: '#14B8A6', sortOrder: 12 },
    { name: 'Monitoring/LogicMonitor', icon: 'activity', color: '#F97316', sortOrder: 13 },
  ];

  for (const pillar of pillars) {
    await prisma.technologyPillar.upsert({
      where: { name: pillar.name },
      update: pillar,
      create: pillar,
    });
  }

  // Create default export templates
  const templates = [
    {
      name: 'Ticket Note',
      type: 'ticket_note',
      isDefault: true,
      content: `# Ticket Note: {{title}}

**Client:** {{client}}
**Ticket ID:** {{ticketId}}
**Priority:** {{priority}} | **Status:** {{status}}
**Category:** {{category}}
**Date:** {{createdAt}}

---

## Symptoms
{{symptoms}}

## Affected Systems
{{impactedService}}

## Quick Notes
{{quickNotes}}

## Resolution
{{resolution.summary}}

### Root Cause
{{resolution.rootCause}}

### Fix Applied
{{resolution.fixApplied}}

### Validation
{{resolution.validationSteps}}

---
*Time Spent: {{resolution.timeSpentMinutes}} minutes*
`,
    },
    {
      name: 'Handoff Document',
      type: 'handoff',
      isDefault: true,
      content: `# Handoff Document

**Client:** {{client}}
**Ticket:** {{title}} ({{ticketId}})
**Date:** {{date}}
**From:** {{user}}

---

## Current Status
{{status}}

## Summary
{{resolution.summary}}

## What Was Done
{{resolution.fixApplied}}

## What Remains
{{resolution.handoffNotes}}

## Open Tasks
{{tasks}}

## Important Notes
- Sensitivity: {{sensitivity}}
- Affected Users: {{affectedUsers}}

---
*Generated by MSP Ops Dashboard*
`,
    },
    {
      name: 'Change Plan',
      type: 'change_plan',
      isDefault: true,
      content: `# Change Plan

**Client:** {{client}}
**Change Title:** {{title}}
**Requested By:** {{user}}
**Date:** {{date}}

---

## Description of Change
{{description}}

## Justification
{{quickNotes}}

## Impact Assessment
- **Affected Service:** {{impactedService}}
- **Affected Users:** {{affectedUsers}}
- **Outage Expected:** {{isOutage}}

## Implementation Steps
1. 
2. 
3. 

## Rollback Plan
1. 
2. 

## Validation Steps
{{resolution.validationSteps}}

## Schedule
- **Planned Start:** 
- **Planned End:** 
- **Maintenance Window:** 

---
*Generated by MSP Ops Dashboard*
`,
    },
    {
      name: 'Post-Incident Report',
      type: 'pir',
      isDefault: true,
      content: `# Post-Incident Report

**Client:** {{client}}
**Incident:** {{title}} ({{ticketId}})
**Severity:** {{priority}}
**Date:** {{date}}

---

## Executive Summary
{{resolution.summary}}

## Timeline
| Time | Event |
|------|-------|
| {{detectedAt}} | Incident Detected |
| {{acknowledgedAt}} | Acknowledged |
| {{mitigatedAt}} | Mitigated |
| {{resolvedAt}} | Resolved |

## Root Cause
{{resolution.rootCause}}

## Impact
- **Service Affected:** {{impactedService}}
- **Users Affected:** {{affectedUsers}}
- **Outage Duration:** {{outageDuration}}

## Resolution
{{resolution.fixApplied}}

## Prevention
{{resolution.prevention}}

## Lessons Learned
1. 
2. 

## Action Items
{{tasks}}

---
*Generated by MSP Ops Dashboard*
`,
    },
  ];

  for (const template of templates) {
    await prisma.exportTemplate.upsert({
      where: { name: template.name },
      update: template,
      create: template,
    });
  }

  // Create sample clients
  const sampleClients = [
    { name: 'Contoso Ltd', acronym: 'CON', envType: 'hybrid', envTags: ['Azure', 'AD DS', 'VMware'] },
    { name: 'Fabrikam Inc', acronym: 'FAB', envType: 'azure', envTags: ['Azure', 'Entra ID'] },
    { name: 'Northwind Traders', acronym: 'NWT', envType: 'on-prem', envTags: ['AD DS', 'Windows Server', 'VMware'] },
  ];

  for (const client of sampleClients) {
    await prisma.client.upsert({
      where: { acronym: client.acronym },
      update: client,
      create: client,
    });
  }

  console.log('Seed data created successfully');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
